# Generated by Django 5.1.4 on 2026-05-30 18:30

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usermovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="usermovie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="movies_movi_title_652549_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["rating"], name="movies_movi_rating_8fd49a_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date"], name="movies_movi_release_b7ac7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="movie_search_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="movie_title_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(fields=["name"], name="movies_acto_name_2656bd_idx"),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="actor_search_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="actor_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "movie")},
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "movie")},
        ),
    ]
