# Generated by Django 5.1.4 on 2026-06-02 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "first_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_from",
                        to="movies.movie",
                    ),
                ),
                (
                    "second_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_to",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["first_movie", "-score"],
                        name="movies_movi_first_m_99cd9d_idx",
                    )
                ],
                "unique_together": {("first_movie", "second_movie")},
            },
        ),
    ]
