# Generated by Django 5.1.4 on 2026-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_moviesimilarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
