# Generated by Django 5.1.4 on 2026-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_moviesimilarity"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Говорим Django обновить внутреннюю структуру моделей (State)
                migrations.AddField(
                    model_name="review",
                    name="is_deleted",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[
                # Оставляем этот список абсолютно ПУСТЫМ.
                # Никаких SQL-запросов (ALTER TABLE ADD COLUMN) к базе на Railway выполняться не будет.
            ]
        ),
    ]