[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn movie_recommender.wsgi --workers 4 --threads 2 --timeout 30 --log-file -"
healthcheckPath = "/"
restartPolicyType = "on_failure"
